name: cortography

channels:
  - conda-forge

dependencies:
  - ruby
  - pip
  - pip:
    - numpy==1.16.*
    - matplotlib==3.*
    - pandas
    - scipy
    - notebook
    - atlasreader
    - nilearn
    - tqdm
